### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pgleeson**
@cengique, hoping to do a bit of work on this project & conversion to NeuroML2 together with Boris Marin here and a student volunteer in Germany. Ok to get write access to this repository?

### CODE REVIEW

**Comment by cengique** [comment]
I added you to the project. I'd be happy if you guys can contribute a NeuroML2 version of the model. Let me know if you need any input from me. Best,
-Cengiz

**Comment by pgleeson** [comment]
Thanks @cengique!

**Comment by jrieke** [comment]
@cengique Hi, I am the student from Germany @pgleeson mentioned. Can you also give me access? Best, Johannes

**Comment by cengique** [comment]
@jrieke Hi Johannes! I just added you as collaborator. Let me know if I can help in any other way and thanks again for working on this model.  Cheers.

**Pull request merged**
